<?php

namespace FilmsBundle\Repository;

/**
 * FilmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilmRepository extends \Doctrine\ORM\EntityRepository
{
    public function listeFilms()
    {
        return $this->createQueryBuilder('f')->orderBy('f.position', 'ASC')->getQuery()->getResult();
    }
    public function positionInitiale($id)
    {
        return $this->getEntityManager()->createQueryBuilder()->select('f.position')->from('FilmsBundle:Film', 'f')
                    ->where('f.id = :id')->setParameter('id', $id)->getQuery()->getSingleScalarResult();
    }
}
